helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.14.4
    releaseName: cert-manager
    # namespace: cert-manager
    valuesInline:
      installCRDs: true
      serviceAccount:
        create: true
        name: cert-manager
      replicaCount: 1
      extraArgs:
        - --v=3
        - --enable-certificate-owner-ref=true